# Generated by Django 3.1.1 on 2020-11-22 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_in_like', to='network.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_in_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
